function Hd = BPF
%BPF Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.6 and the Signal Processing Toolbox 6.9.
%
% Generated on: 20-May-2013 14:26:44
%

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 50;  % Sampling Frequency

N      = 50;   % Order
Fstop1 = 2.5;  % First Stopband Frequency
Fpass1 = 3;    % First Passband Frequency
Fpass2 = 7;    % Second Passband Frequency
Fstop2 = 7.5;  % Second Stopband Frequency
Wstop1 = 0.1;  % First Stopband Weight
Wpass  = 1;    % Passband Weight
Wstop2 = 0.1;  % Second Stopband Weight
dens   = 20;   % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2], {dens});
Hd = dfilt.dffir(b);
set(Hd, 'Arithmetic', 'double');

% [EOF]
